name: Cache Test

on: [push]

jobs:
  test-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Restore cache
        id: cache
        uses: actions/cache@v3
        with:
          path: test-cache
          key: ${{ runner.os }}-cache-test

      - name: Create dummy file
        run: |
          mkdir -p test-cache
          echo "Prueba de cache" >> test-cache/file.txt

      - name: Show cache contents
        run: ls -R test-cache

